### ISSUE TITLE
Filename goes out from side bar

### ISSUE THREAD

**Issue by ikasty** [poucotm/Guna#1]
![image](https://user-images.githubusercontent.com/5230659/36057763-34e8efe0-0e56-11e8-9754-d596027a39c9.png)
If width of side bar is smaller than file names, names are displayed over the side bar margin.

Using latest version of Guna, ST3 3143.

**Comment by poucotm** [comment]
It ia not a bug. You can use double-click on the boundary to fit sidebar width automatically.
