### ISSUE TITLE
set console font size

### ISSUE THREAD

**Issue by JackMing0** [poucotm/Guna#10]
Hello, blogger, I like your theme very much! I am also writing a plugin recently! Wonder how you set up Sublime Text's console font size!
![222](https://user-images.githubusercontent.com/37831370/60645502-6bdf5b00-9e6b-11e9-8854-71d08badf700.png)

**Comment by poucotm** [comment]
You can control using widget sublime-settings. If it is not specified in widget settings, it will be the same in preference settings.

**Comment by JackMing0** [comment]
Thank you very much bloggers! Solved a problem I hadn't solved for a long time! I've been working on a code completion prompt preview plugin recently, and bloggers know how to listen to the list menu that pops up with code completion autocomplete! When I move up and down! Get the code item inside! Deal with it! Or how to create such a list menu! To display the items you need! If you know or have any Suggestions! Please help me! In this thanks
![333](https://user-images.githubusercontent.com/37831370/60673468-58071980-9eaa-11e9-9d6f-b6dc3b99d3fa.png)

**Comment by poucotm** [comment]
You can use sublime_plugin.EventListener on_query_completions(). I think you can get great answers here - https://forum.sublimetext.com :-)

**Comment by JackMing0** [comment]
Thanks for your reply! I've read the sublime official documentation and BBS and can't find anything that meets the requirements! Sublime's API is quite a pity! Not powerful! Only a simple way to do it! Can't make more advanced plugins!

I've gotten around that! Solve the problem from the side!

I read the blogger you wrote this plugin! Some features I need!
Sublime's sidebar! When the mouse moves over the file, it lights up the file! This place is supposed to have an event!

Can you help me? I want to listen for open files in the sidebar! For example: when the mouse click on the file in the sidebar, listen to what file is open!



![000](https://user-images.githubusercontent.com/37831370/61004945-b8f68c00-a399-11e9-9953-9acd1bcd0995.png)
