### ISSUE TITLE
GUNA: ERROR ___ keyError: 'dt'

### ISSUE THREAD

**Issue by JKaminsky1988** [poucotm/Guna#13]
hi!
what does this error mean?
how i can resolve this problem?
and is pouco? my user name is different
![изображение](https://user-images.githubusercontent.com/35423782/70224056-3fe73f00-1755-11ea-9d51-54cd24021715.png)

**Comment by poucotm** [comment]
Don't care about that. It is just the information before compilation. The error means there is some problem of reading weather information dt (date time) from '.weather' file. You can check the file in sublime.cache_path()/Guna/cache folder.
