### ISSUE TITLE
query weather by geographic coordinates  

### ISSUE THREAD

**Issue by lihy2005** [poucotm/Guna#14]
Hi there, thank you for the awesome theme, really enjoyed it. One small problem tho, not all cities been listed or have unique names in openweathermap's database, so is it possible to update the weather settings to use different query methods like [geographic coordinates or zip code](https://openweathermap.org/current)?
https://openweathermap.org/current

Cheers,

**Comment by poucotm** [comment]
I added the option (v1.7.6). please, try to set like "geographic": {"lat":35, "lon":139} instead of "city_name".

**Comment by lihy2005** [comment]
> I added the option (v1.7.6). please, try to set like "geographic": {"lat":35, "lon":139} instead of "city_name".

Thank you so much!
