### ISSUE TITLE
how to make clock and weather together in a single line ?

### ISSUE THREAD

**Issue by wensonsmith** [poucotm/Guna#15]
I don't like use `shift + esc ` to change display, i want weather show behind the clock , 

so is there a way to approach it ?

thank you very much !

![image](https://user-images.githubusercontent.com/2544185/71571482-71191c00-2b15-11ea-8e8c-f2ab56f58349.png)

**Comment by poucotm** [comment]
Sorry, it is impossible... (__).

**Comment by wensonsmith** [comment]
OK... it's still a great theme 🌹
