### ISSUE TITLE
urllib.error.HTTPError: HTTP Error 401: Unauthorized

### ISSUE THREAD

**Issue by almoce** [poucotm/Guna#17]
weather widget not working.

**Comment by poucotm** [comment]
Maybe you need to get correct APPID first.

**Comment by LukeGary462** [comment]
can you provide an example of a proper setting for 
```
"weather": {
    "appid": 'what exactly goes here`
}
```

obviously you can omit your apikey, but formatting for reference on the top-level readme would be helpful

**Comment by poucotm** [comment]
If you got the appid already, just put your addid only like this.
`"appid" :  "xxxxxxxxxxxxxxxxxxxxxxxxxxx"`

You can also check your appid by your web browser : 
`http://api.openweathermap.org/data/2.5/weather?q=seoul,KR&APPID=xxxxxxxxxxxxxxxxxxx`

This is an example of response  : 
`{"coord":{"lon":127.14,"lat":37.44},"weather":[{"id":721,"main":"Haze","description":"haze","icon":"50d"}],"base":"stations","main":{"temp":297.19,"feels_like":297.11,"temp_min":296.15,"temp_max":298.15,"pressure":1013,"humidity":69},"visibility":9000,"wind":{"speed":4.1,"deg":230},"clouds":{"all":75},"dt":1591498475,"sys":{"type":1,"id":8096,"country":"KR","sunrise":1591474241,"sunset":1591527012},"timezone":32400,"id":1897000,"name":"Seongnam-si","cod":200}`

![image](https://user-images.githubusercontent.com/19210389/83959317-78a7d280-a8b6-11ea-9cb0-0fae6a1b0fe8.png)
