### ISSUE TITLE
Panel control border

### ISSUE THREAD

**Issue by Augiiz** [poucotm/Guna#18]
Running guna theme with sublimelinter plugins panel doesn't look great for the panel because it blends into code and what not, really needs a border (in my opinion).
Sure it's possible to play with theme file, but some fix would be nice, at least an option in user settings file.
![image](https://user-images.githubusercontent.com/7473667/78838336-a085d180-79fe-11ea-9a99-7d773be004d6.png)

**Comment by poucotm** [comment]
I updated for panel control border. The border can be seen on any color scheme.
You can check v1.7.8 version for it.

![image](https://user-images.githubusercontent.com/19210389/79342488-2ad2b600-7f68-11ea-9e3a-3698ebc5ca0e.png)

**Comment by Augiiz** [comment]
Sweet fix, thanks!
