### ISSUE TITLE
Options for styling scroll_bar

### ISSUE THREAD

**Issue by BramVer** [poucotm/Guna#2]
The theme is pretty with everything very flat, only the scroll_bar feels completely out of touch.
Are there any options to change its appearance, rather than just color?
Things like the color gradient, the roundness and such, don't feel like they belong in this theme so I'd very much like to style this more to my liking :)

**Comment by BramVer** [comment]
I'd look into a more Material style -> flat rectangle without a color gradient.
It's just personal preference, but I feel like it wouldn't clash with the theme.

**Comment by poucotm** [comment]
I added flat-style scroll-bars as default. v1.6.0.
