### ISSUE TITLE
No Documentation on how to put clock into 12 hour mode

### ISSUE THREAD

**Issue by Jadens-arc** [poucotm/Guna#23]
I've searched through all your documentation and forum posts and all I know is that this feature was added in version 1.7.

**Comment by poucotm** [comment]
@Jadens-arc , Sorry, it was deprecated since v1.10.0 when changing widget style all (clock,date,weather).

**Comment by Jadens-arc** [comment]
@poucotm, Thanks I've been going crazy trying to find a solution

**Comment by poucotm** [comment]
@Jadens-arc , I've recovered "sidebar_widget_clock_mode": "24h" setting (v1.11.5). But it doesn't display 'AM/PM' like before.
