### ISSUE TITLE
No image on the left from command panel

### ISSUE THREAD

**Issue by krupitskas** [poucotm/Guna#24]
<img width="118" alt="Снимок экрана 2020-08-12 в 22 56 06" src="https://user-images.githubusercontent.com/5683877/90061643-15d81a80-dcef-11ea-95a7-79a97980a6d8.png">
I mean this one.

I've just installed package. Build 4081

**Comment by poucotm** [comment]
@krupitskas , I think it is related sublime version. I'm not testing sublime 4 yet.

**Comment by poucotm** [comment]
@krupitskas , Hmm, it also works for sublime build 4081 (windows).

![image](https://user-images.githubusercontent.com/19210389/90138265-b727a500-ddb1-11ea-9bab-665ef5c25da7.png)

**Comment by krupitskas** [comment]
Ah, sorry, forgot to mention operating system - its macos catalina 10.15.6

**Comment by krupitskas** [comment]
<img width="459" alt="Снимок экрана 2020-08-13 в 16 16 28" src="https://user-images.githubusercontent.com/5683877/90138964-6186d480-dd80-11ea-808d-849c3c2a1e2c.png">
