### ISSUE TITLE
Clock Never Appears

### ISSUE THREAD

**Issue by WPLibrary** [poucotm/Guna#25]
Hi,

[![Screen-Shot-2020-08-28-at-19.13.05bf6efa58ee0f4f5a.png](https://s3.imgbu.com/file/imgbucom-s/2020/08/28/Screen-Shot-2020-08-28-at-19.13.05bf6efa58ee0f4f5a.png)](https://imgbu.com/i/RWyrD)

As you see, the clock field doesn't appear at all.

I use Guna with Ayu color schema. Here is my Sublime settings:
```
{
	"auto_complete_commit_on_tab": true,
	"auto_complete_with_fields": true,
	"close_windows_when_empty": true,
	"color_scheme": "Packages/ayu/ayu-mirage.sublime-color-scheme",
	"folder_exclude_patterns":
	[
		"node_modules"
	],
	"font_size": 15.8,
	"gn_hide_tab_dropdown": true,
	"gn_overlay_scroll_bars": true,
	"gn_sb_cnvx": true,
	"gn_sidebar_box": true,
	"gn_title_bar": true,
	"gnc_001": false,
	"gnc_002": false,
	"gnc_h19": true,
	"gnc_m01": true,
	"gnc_w4m11": true,
	"gnwidg1": true,
	"gpu_window_buffer": false,
	"ignored_packages":
	[
		"CSS",
		"Vintage"
	],
	"save_on_focus_lost": true,
	"tab_size": 2,
	"theme": "Guna.sublime-theme",
	"trim_automatic_white_space": false,
	"word_wrap": "true"
}
```

Thanks in advance.

**Comment by poucotm** [comment]
@WPLibrary, Hi, just strech out the sidebar. It looks too narrow to display the clock. Simply, you can double click on the sidebar boundary to strech out.

**Comment by WPLibrary** [comment]
@poucotm it was a stupid mistake :) works properly now! Thanks for the help and this amazing theme!
