### ISSUE TITLE
코드 자동완성 하이딩

### ISSUE THREAD

**Issue by dlrpfl** [poucotm/Guna#27]
guna 테마 사용 중 코드 자동완성 박스가 사라집니다.

**Comment by poucotm** [comment]
항상 그런가요?

**Comment by dlrpfl** [comment]
> 항상 그런가요?

현재 2.5.0 버전 다운받아서 수동으로 설치하고 사용중인데 정상 작동합니다.

근데 서브라임텍스트 내에서 패키지 최신버전 설치하면 위 현상이 발생합니다.

**Comment by poucotm** [comment]
Windows 10, Sublime Text 3 or 4 모두 자동 완성이 사라지는 현상은 안보이네요.
자동 완성이 사라질때, Console (ctrl + `) 화면에서 별다른 메시지는 없나요?

**Comment by dlrpfl** [comment]
콘솔창에 별다른 메시지 없습니다.

정확히 말하자면 제목표시줄이 계속 깜빡거리면서 위 현상이 발생합니다.

**Comment by poucotm** [comment]
흠, 현상을 볼 수가 없어, 어떤 문제인지 모르겠습니다.
다른 plug-in 과 충돌 가능성은 없을 까요?

**Comment by dlrpfl** [comment]
현재 사용중인 패키지

![캡처](https://user-images.githubusercontent.com/70948673/93606434-04c3ad00-fa03-11ea-8762-c1095e3e4b76.PNG)

**Comment by poucotm** [comment]
@dlrpfl , 문제를 찾았어요. ^^.  Color-scheme 을 Guna 외 다른 걸 사용할 때 dirty status 를 표시하는데, 문제가 있었습니다.
다른 plug-in 과의 충돌은 아닙니다. 지금도 Guna Color Scheme 을 선택하면 현상이 없을 거에요. 아무튼 해당 코드는 patch 했습니다. packagecontrol.io 에 2-3 시간내에 v2.8.3 이 업데이되면 사용해보세요. 덕분에 버그를 찾았네요.

**Comment by dlrpfl** [comment]
좋은 플러그인 공유 감사합니다.

좋은 주말 보내세요 :)

**Comment by poucotm** [comment]
Sublime Text 를 껐다 다시 켜도 같은 현상인가요?
특별한 조건일 때 일어나진 않나요?
SideBar 에서 시계 위젯을 사용하시나요?
깜빡임이 편집중에 발생하는 색표시(핑크) 와 일반(노랑) 이 반복되는 현상인가요?

리스트에 언급된 package 를 다 설치해봤는데, 이상은 없었습니다.

**Comment by dlrpfl** [comment]
껐다 켜도 같은 현상 발생하고, 편집중이 아니어도 나타나네요.

clock,date,weather 위젯 사용중입니다.

**Comment by dlrpfl** [comment]
> 깜빡임이 편집중에 발생하는 색표시(핑크) 와 일반(노랑) 이 반복되는 현상인가요?

이 말은 무슨 말인지 잘 이해가 안가네요..ㅠㅜㅠ

**Comment by dlrpfl** [comment]
혹시 이게 도움이 될지는 모르겠지만 

2.7.2 버전부터 들어간 gpu_window_buffer 이 기능이 추가된 버전부터 현상이 발생하는 것 같습니다.

gpu_window_buffer기능이 아직 추가 안된 아래 버전들은 정상 작동하는 것 같습니다!

**Comment by dlrpfl** [comment]
도움이 될지는 모르겠지만,

2.6.2 버전부터 현상 발생하는 것 같습니다. 2.6.2 아래 버전부터는 정상 작동합니다.

**Comment by poucotm** [comment]
@dlrpfl , 관련 code 를 patch 했어요. v2.8.5 로 확인해주세요. 감사합니다.

**Comment by dlrpfl** [comment]
2.8.5버전 정상 작동 확인했습니다!

공짜로 쓰는 주제에 주말에 일을 시킨 것 같은 죄책감이 드네요.. 테마 너무 이뻐요. 좋은 플러그인 공유 감사드립니다.

코로나로 힘든 시기 힘내시고 다가올 추석 연휴 잘 보내시길 바라겠습니다!

**Comment by poucotm** [comment]
@dlrpfl 덕분에 인식하지 못하던 버그를 찾아서 많은 도움이 됐어요. 한글로 이슈가 적힌게 처음이라, 처음에는 외국분이 번역기로 적은 줄 알았어요ㅋ 좋은 주말되세요
