### ISSUE TITLE
Change background colour of the dark Guna theme

### ISSUE THREAD

**Issue by javier-cazana** [poucotm/Guna#28]
Hi there @poucotm 

This is a FANTASTIC theme. I love it. I was wondering if is possible to change just the background of the Guna dark theme (preserve all the rest) to something just a bit less darker. 

If not is still brilliant, my favourite theme!

Cheers

**Comment by poucotm** [comment]
@javier-cazana, You can change the background color of the original Guna color scheme here -  Preferences > Package Settings > Guna > settings
```
/*  Guna Color Scheme _________________________________________
*/

	// background color
	"guna_bgcolor": "#161C23", // use "#131B1F" when too bluish
	// indent guide
	"guna_guide": "#20272E",
```
