### ISSUE TITLE
Choosing a color scheme from a project file

### ISSUE THREAD

**Issue by Savanlars** [poucotm/Guna#29]
Great theme, but doesn't support choosing a color scheme from a project file.

**Comment by poucotm** [comment]
It is possible by getting a property from a project file. Do you need it ?  Do you know the property name commonly used ?

**Comment by Savanlars** [comment]
It's not that important anymore. The Guna had to be removed. Becose i'm work from a flash drive. This theme constantly writing something to disk... I guess some condition checks are missing. For example:

`if not os.path.exists(loadnum): open(loadnum, 'w'). Close()`

etc...

P.S. Sorry for my bad english, wrote with translator.
