### ISSUE TITLE
Is it possible to support native tabs on mac?

### ISSUE THREAD

**Issue by ciaoben** [poucotm/Guna#30]
When using the default theme, and having multiple windows opened on the mac you get the native project tabs. So you have all the sublime windows in a unique OS window. But when enabling this theme that feature is missing. Is it possible to restore it?

**Comment by poucotm** [comment]
@ciaoben , I don't understand what you mean. Basically, Guna is based on sublime-theme scheme. It isn't able to make functional difference from default theme.

![image](https://user-images.githubusercontent.com/19210389/100226099-96e7b480-2f62-11eb-86b7-f767dff25721.png)

**Comment by ciaoben** [comment]
@poucotm sorry, I have not been very clear.

Here what I love about the Sublime default theme:

![image](https://user-images.githubusercontent.com/4526061/100232283-7864c780-2f28-11eb-9dbb-fa56772af65c.png)


As you can see, if I have two opened project I get the native tabs to easily switch between them.

When I open two projects with Guna, I get two separate windows!

**Comment by poucotm** [comment]
@ciaoben, Now I know what macos tab is. However, it looks working as you can see.

MacOS tabs w/ Default Theme

![image](https://user-images.githubusercontent.com/19210389/100351389-b8ae6d80-302e-11eb-974f-d075660e0c86.png)

MacOS tabs w/ Guna Theme

![image](https://user-images.githubusercontent.com/19210389/100351500-de3b7700-302e-11eb-8b5f-cac4542c065b.png)

**Comment by ciaoben** [comment]
> @ciaoben, Now I know what macos tab is. However, it looks working as you can see.
> 
> MacOS tabs w/ Default Theme
> 
> ![image](https://user-images.githubusercontent.com/19210389/100351389-b8ae6d80-302e-11eb-974f-d075660e0c86.png)
> 
> MacOS tabs w/ Guna Theme
> 
> ![image](https://user-images.githubusercontent.com/19210389/100351500-de3b7700-302e-11eb-8b5f-cac4542c065b.png)

I can't make it work, when I switch theme to Guna and restart sublime all the tabs are splitted in different unlinked windows

**Comment by poucotm** [comment]
@ciaoben , I've found this issue here : https://github.com/sublimehq/sublime_text/issues/1797
It is not an only Guna theme issue and related with title bar background coloring.
For sublime, you cannot use title bar coloring and native tabs at the same time.
I updated the codes to support native tabs (v3.0.7). You have to set 'title_bar_color' as false.
