### ISSUE TITLE
Colors are dull

### ISSUE THREAD

**Issue by Biskweet** [poucotm/Guna#31]
I love Guna and have been using it for months now.
But when I opened it 2-3 days ago, I immediately saw the colors of the color scheme were dull (different than usual).
![image](https://user-images.githubusercontent.com/67809939/100457657-bf86c000-30c2-11eb-8a3f-7ec3dc07e4cc.png)

I can't understand why. I tried doing a clean reinstall of Sublime Text then of Guna, and still.

**Comment by poucotm** [comment]
@Biskweet , I changed the default saturation/brightness 3 days ago. By changing two settings like the following, you can see original colors. (Preferences > Package Settings > Guna > Settings)
```
   "guna_color_saturation" : 100
   "guna_color_brightness" : 100
```
