### ISSUE TITLE
Guna 테마와 다른 color scheme 사용중 command palette 에러

### ISSUE THREAD

**Issue by dlrpfl** [poucotm/Guna#32]
Guna 테마와 다른 color scheme 사용중 command palette 창 입력박스 부분이 테두리가 생기면서 깜빡거립니다.

**Comment by poucotm** [comment]
지난번 그분이군요ㆍ어떤컬러스킴을 쓰시나요? 현상을 보여줄 수 있나요?

**Comment by dlrpfl** [comment]
brogrammer 사용하고 있습니다. guna 컬러스킨 외 컬러스킨은 전부 다 위 현상이 발생합니다. 

깜빡거리는게 너무 빨라서 캡처를 못하겠습니다

**Comment by poucotm** [comment]
이상하네요ㆍconsole 창 ctrl+` 에는 별메시지가 없나요?

**Comment by dlrpfl** [comment]
console 창은 문제 없고 console창에 에러 메시지 없습니다

**Comment by dlrpfl** [comment]
![screenshot](https://user-images.githubusercontent.com/70948673/110759393-e98a7980-8290-11eb-8cde-f8cf8d06b9b6.PNG)

위 이미지처럼 입력박스 주위에 색상이 계속 깜빡거립니다
