### ISSUE TITLE
Weather widget is not showing

### ISSUE THREAD

**Issue by yahoyoungho** [poucotm/Guna#34]
Sublime의 Preferences > Package Settings > Guna > Settings 에서 원본 Guna.sublime-settings 파일을 복사 후 옆에서 appid 와 city_name에 정보를 넣었는데 날씨 정보가 뜨지 않습니다.

제가 쓰고 있는 sublime의 build는 4113입니다. 도움을 주실 수 있으시면 정말 감사하겠습니다.

**Comment by yahoyoungho** [comment]
sidebar_widget 변수를 수정해야하는지 몰랐습니다. 감사합니다!

**Comment by poucotm** [comment]
Guna.sublime-settings 파일을 복사할 필요는 없어요. Preferences > Package Settings > Guna > Settings 하고 오른쪽에, 필요한 Setting 만 업데이트하면 되요.
