### ISSUE TITLE
customizable clock?

### ISSUE THREAD

**Issue by keenahn** [poucotm/Guna#35]
Love the theme and the widgets! 

I noticed that you're using images for the clock. I understand that's an easy way to get it to display correctly in all environments, but have you considered adding just a text clock? That would make it way more customizable with fonts, time formats, etc.

thank you! 🙏🏼

**Comment by keenahn** [comment]
Also I notice that you're shipping with compiled `.pyc` files for core and engine. Would you consider releasing the source files for this? I'd love to take a look :)

**Comment by poucotm** [comment]
You can change it. it's been open since 2023.2.
