### ISSUE TITLE
Bug or not? Not Respond in Sublime Text

### ISSUE THREAD

**Issue by Veagau** [poucotm/Guna#37]
When I lauch the Sublime Text after activating the Guna, there will be no response for a while(about 3~5 seconds).

Sublime Text: Build 4126.

**Comment by Jagerx** [comment]
the same issue on 4126 by using Guna. The SublimeText windows freeze for 3-5 seconds every time when I launch it. and will crash if keep clicking on the SublimeText windows

**Comment by schwrzstrbn** [comment]
Same problem

Sublime-text build: 4126

**Comment by poucotm** [comment]
Hi, All,
I removed that initial delay (v4.2.0). Please, update the package.

**Comment by Jagerx** [comment]
> Hi, All,
> I removed that initial delay (v4.2.0). Please, update the package.

It works well now. thanks a lot
