### ISSUE TITLE
A File Icons is no longer in package control. replacement?

### ISSUE THREAD

**Issue by asamolion** [poucotm/Guna#6]
[A File Icons](https://packagecontrol.io/packages/A%20File%20Icon) is stated as `missing` on Package Control. The repo has also been removed from github by the creator.

[FileIcons](https://packagecontrol.io/packages/FileIcons) by braver is an alternative however it requires some manual tweaking.
@poucotm 
How important would you say is having custom file icons for Guna?

If you believe its a feature that should be included I'm willing to work on it if you'd like.

Regards,
Osama Arshad

**Comment by poucotm** [comment]
@asamolion, It is recommended, not necessary. Guna doesn't have own file icons. You can use others you like ~.
