### ISSUE TITLE
Sidebar group labels are invisible

### ISSUE THREAD

**Issue by Igonato** [poucotm/Guna#7]
Guna:
![image](https://user-images.githubusercontent.com/788609/53319858-dcd29d00-38e4-11e9-9f69-5fb790a2accb.png)
Sublime's Adaptive theme:
![image](https://user-images.githubusercontent.com/788609/53319993-43f05180-38e5-11e9-850c-b93f3cec6a21.png)

**Comment by poucotm** [comment]
You can control show/hide sidebar heading on v1.6.12 with settings.

	// Show/Hide sidebar heading
	"sidebar_head": false,
	....
	"sidebar_head.color": "#D9D7CE",
