### ISSUE TITLE
Sidebar scrollbar bug

### ISSUE THREAD

**Issue by Antroll** [poucotm/Guna#8]
![scrollbar](https://user-images.githubusercontent.com/15137898/53682894-caf15f80-3d13-11e9-9202-9b1c253d05ae.png)

**Comment by poucotm** [comment]
It has been fixed up on v1.6.11

**Comment by Antroll** [comment]
Taking this opportunity, I would like to thank you for this wonderful color theme. I use it for about a year probably.
